### ISSUE TITLE
BUG : RudderStack requirements.txt prevent projects from using python-dotenv 1.0.0 or later

### ISSUE THREAD

**Issue by burgaard** [rudderlabs/rudder-sdk-python#30]
The Python SDK currently restricts python-dotenv to less than version 1.0.0:

```
python-dotenv>=0.21.0, <1.0.0
```

However, python-dotenv 1.0.0 was released over a year ago (Feb 23, 2023), and the latest version is 1.0.1.

From python-dotenv's change log https://github.com/theskumar/python-dotenv/blob/main/CHANGELOG.md it seems there should be no issue for RudderStack to remove the upper limit, or bump it to, say, 2.0.0:

```
python-dotenv>=0.21.0, <2.0.0
```

**Comment by itsdebs** [comment]
@burgaard Thanks for reporting. We will be releasing the next version with the fixes.

**Comment by Elijas** [comment]
https://github.com/theskumar/python-dotenv/releases
Note: No breaking changes in v1.0.0, it just was declared "stable"

**Comment by josead** [comment]
Same issue here, please can someone fix this?

**Comment by itsdebs** [comment]
We have released v2.1.0 with the fix. Thank you for your inputs

**Comment by burgaard** [comment]
@itsdebs I just tried upgrading to rudder-sdk-python 2.1.0, but I still get the same version conflict suggesting the updated requirement.txt didn't make into the package:

```
ERROR: Cannot install -r requirements.txt (line 89), python-dotenv==1.0.1 and rudder-sdk-python==2.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested python-dotenv==1.0.1
    pydantic-settings 2.2.1 depends on python-dotenv>=0.21.0
    rudder-sdk-python 2.1.0 depends on python-dotenv<0.22.0 and >=0.21.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by itsdebs** [comment]
@burgaard thank you for reporting this. Looking into it.

**Comment by slothyrulez** [comment]
@itsdebs A new version has been released but the lib still requires `python-dotenv<0.22.0`

**Comment by engsmith** [comment]
https://github.com/rudderlabs/rudder-sdk-python/pull/34/
